
import { Service, Translation, Order, Course, ServiceCategory, InfoPage, Project, BlogCategory, BlogPost, Review } from './types';

export const EXCHANGE_RATE = 3.75;

export const TRANSLATIONS: Translation = {
  appName: { en: 'Namaa', ar: 'نماء' },
  tagline: { en: 'Business Setup & Growth Platform', ar: 'منصة تأسيس ونمو الأعمال' },
  home: { en: 'Home', ar: 'الرئيسية' },
  company: { en: 'Company', ar: 'الشركة' },
  support: { en: 'Support', ar: 'الدعم' },
  services: { en: 'Services', ar: 'الخدمات' },
  projects: { en: 'Ready Projects', ar: 'مشاريع جاهزة' },
  blog: { en: 'Blog', ar: 'المدونة' }, 
  contact: { en: 'Contact Us', ar: 'اتصل بنا' },
  readMore: { en: 'Read More', ar: 'اقرأ المزيد' },
  latestArticles: { en: 'Latest Articles', ar: 'أحدث المقالات' },
  blogDesc: { en: 'Insights and guides for your business journey.', ar: 'رؤى وأدلة لرحلة مشروعك التجاري.' },
  manageBlog: { en: 'Manage Blog', ar: 'إدارة المدونة' },
  blogCategories: { en: 'Blog Categories', ar: 'تصنيفات المدونة' },
  addPost: { en: 'Add Article', ar: 'إضافة مقال' },
  editPost: { en: 'Edit Article', ar: 'تعديل المقال' },
  postTitleAr: { en: 'Article Title (Arabic)', ar: 'عنوان المقال (عربي)' },
  postTitleEn: { en: 'Article Title (English)', ar: 'عنوان المقال (إنجليزي)' },
  latestServices: { en: 'Latest Services', ar: 'أحدث الخدمات' },
  latestCourses: { en: 'Latest Training Courses', ar: 'أحدث الدورات التدريبية' },
  latestProjects: { en: 'Ready-made Projects', ar: 'مشاريع برمجية جاهزة' },
  dashboard: { en: 'Dashboard', ar: 'لوحة التحكم' },
  admin: { en: 'Admin', ar: 'مسؤول' },
  client: { en: 'Client', ar: 'عميل' },
  language: { en: 'العربية', ar: 'English' },
  heroTitle: { en: 'Launch and Grow Your Business', ar: 'أطلق وطور مشروعك التجاري' },
  heroSubtitle: { en: 'From company formation to digital dominance, we provide everything you need.', ar: 'من تأسيس الشركة إلى الريادة الرقمية، نوفر لك كل ما تحتاجه.' },
  getStarted: { en: 'Get Started', ar: 'ابدأ الآن' },
  consultAI: { en: 'Al-Mutammam Automated Consultant', ar: 'مستشار المتمم الآلي' },
  setupServices: { en: 'Business Setup', ar: 'تأسيس الأعمال' },
  growthServices: { en: 'Online Growth', ar: 'النمو الرقمي' },
  recentOrders: { en: 'Recent Orders', ar: 'الطلبات الحديثة' },
  revenue: { en: 'Total Revenue', ar: 'إجمالي الإيرادات' },
  activeOrders: { en: 'Active Orders', ar: 'الطلبات النشطة' },
  customers: { en: 'New Customers', ar: 'عملاء جدد' },
  aiPrompt: { en: 'Describe your business idea...', ar: 'صف فكرة مشروعك...' },
  aiButton: { en: 'Generate Insights', ar: 'توليد الأفكار' },
  aiLoading: { en: 'Analyzing...', ar: 'جاري التحليل...' },
  bookNow: { en: 'Book Now', ar: 'احجز الآن' },
  addToCart: { en: 'Add to Cart', ar: 'أضف للسلة' },
  addedToCart: { en: 'Added!', ar: 'تمت الإضافة!' },
  cart: { en: 'Shopping Cart', ar: 'سلة المشتريات' },
  checkout: { en: 'Checkout', ar: 'إتمام الطلب' },
  total: { en: 'Total', ar: 'الإجمالي' },
  emptyCart: { en: 'Your cart is empty', ar: 'سلتك فارغة' },
  emptyCartDesc: { en: 'Browse our services and courses to start.', ar: 'تصفح خدماتنا ودوراتنا للبدء.' },
  continueShopping: { en: 'Continue Shopping', ar: 'مواصلة التسوق' },
  buyNow: { en: 'Buy Now & Download', ar: 'شراء وتحميل فوري' },
  download: { en: 'Download Files', ar: 'تحميل الملفات' },
  liveDemo: { en: 'Live Demo', ar: 'معاينة حية' },
  techStack: { en: 'Technologies', ar: 'التقنيات المستخدمة' },
  status: { en: 'Status', ar: 'الحالة' },
  date: { en: 'Date', ar: 'التاريخ' },
  customer: { en: 'Customer', ar: 'العميل' },
  service: { en: 'Service', ar: 'الخدمة' },
  amount: { en: 'Amount', ar: 'المبلغ' },
  // Order Statuses
  completed: { en: 'Completed', ar: 'مكتمل' },
  pending: { en: 'Under Review', ar: 'تحت المراجعة' },
  awaiting_payment: { en: 'Awaiting Payment', ar: 'بانتظار الدفع' },
  in_progress: { en: 'In Progress', ar: 'جاري التنفيذ' },
  cancelled: { en: 'Cancelled', ar: 'ملغي' },
  
  businessName: { en: 'Suggested Name', ar: 'الاسم المقترح' },
  slogan: { en: 'Slogan', ar: 'الشعار اللفظي' },
  strategy: { en: 'Strategy Steps', ar: 'خطوات الاستراتيجية' },
  currency: { en: 'Currency', ar: 'العملة' },
  sar: { en: 'SAR', ar: 'ر.س' },
  usd: { en: 'USD', ar: '$' },
  theme: { en: 'Theme', ar: 'المظهر' },
  courses: { en: 'Training Courses', ar: 'الدورات التدريبية' },
  buyCourse: { en: 'Buy Course', ar: 'شراء الدورة' },
  includesAttachments: { en: 'Includes Attachments', ar: 'شامل الملحقات' },
  lessons: { en: 'Lessons', ar: 'دروس' },
  duration: { en: 'Duration', ar: 'المدة' },
  courseSubtitle: { en: 'Expert-led video courses with comprehensive resources.', ar: 'دورات فيديو بقيادة خبراء مع موارد شاملة.' },
  popular: { en: 'Most Popular', ar: 'الأكثر رواجاً' },
  purchases: { en: 'Purchases', ar: 'عملية شراء' },
  searchPlaceholder: { en: 'Search services, courses or projects...', ar: 'ابحث عن خدمات، دورات أو مشاريع...' },
  noResults: { en: 'No results found matching your search.', ar: 'لا توجد نتائج تطابق بحثك.' },
  servicesDesc: { en: 'Explore our comprehensive range of services designed to help your business thrive.', ar: 'اكتشف مجموعتنا الشاملة من الخدمات المصممة لمساعدة عملك على الازدهار.' },
  coursesDesc: { en: 'Enhance your skills with our expert-led video training courses.', ar: 'طور مهاراتك مع دوراتنا التدريبية المرئية بقيادة الخبراء.' },
  projectsDesc: { en: 'Ready-made source codes and templates to kickstart your business instantly.', ar: 'أكواد برمجية وقوالب جاهزة للبيع لبدء مشروعك فوراً.' },
  businessCat: { en: 'Business Management', ar: 'إدارة الأعمال' },
  marketingCat: { en: 'Marketing & Growth', ar: 'التسويق والنمو' },
  techCat: { en: 'Technology', ar: 'التقنية' },
  reviews: { en: 'Reviews', ar: 'التقييمات' },
  addReview: { en: 'Add Review', ar: 'أضف تقييم' },
  rating: { en: 'Rating', ar: 'التقييم' },
  yourName: { en: 'Your Name', ar: 'اسمك' },
  yourComment: { en: 'Your Comment', ar: 'تعليقك' },
  submit: { en: 'Submit', ar: 'إرسال' },
  close: { en: 'Close', ar: 'إغلاق' },
  outOf5: { en: 'out of 5', ar: 'من 5' },
  recommendations: { en: 'Smart Recommendations', ar: 'توصيات ذكية' },
  recommendationsDesc: { en: 'Tell us your goal, and our AI will suggest the best services and courses for you.', ar: 'أخبرنا بهدفك، وسيقترح الذكاء الاصطناعي أفضل الخدمات والدورات المناسبة لك.' },
  recommendationPlaceholder: { en: 'e.g., I want to start an e-commerce store...', ar: 'مثال: أريد إنشاء متجر إلكتروني...' },
  getRecommendations: { en: 'Get Suggestions', ar: 'احصل على الاقتراحات' },
  recommendedForYou: { en: 'Recommended For You', ar: 'موصى به لك' },
  whyRecommended: { en: 'Why:', ar: 'السبب:' },
  all: { en: 'All Categories', ar: 'جميع الأقسام' },
  categories: { en: 'Categories', ar: 'التصنيفات' },
  courseCategories: { en: 'Course Categories', ar: 'تصنيفات الدورات' },
  addCategory: { en: 'Add Category', ar: 'إضافة تصنيف' },
  editCategory: { en: 'Edit Category', ar: 'تعديل تصنيف' },
  deleteCategory: { en: 'Delete Category', ar: 'حذف تصنيف' },
  categoryNameAr: { en: 'Arabic Name', ar: 'الاسم بالعربية' },
  categoryNameEn: { en: 'English Name', ar: 'الاسم بالإنجليزية' },
  categoryDescAr: { en: 'Arabic Description', ar: 'الوصف بالعربية' },
  categoryDescEn: { en: 'English Description', ar: 'الوصف بالإنجليزية' },
  categoryColor: { en: 'Color Theme', ar: 'لون التصنيف' },
  categoryIcon: { en: 'Category Icon', ar: 'أيقونة التصنيف' },
  categoryOrder: { en: 'Display Order', ar: 'ترتيب العرض' },
  save: { en: 'Save', ar: 'حفظ' },
  cancel: { en: 'Cancel', ar: 'إلغاء' },
  actions: { en: 'Actions', ar: 'إجراءات' },
  overview: { en: 'Overview', ar: 'نظرة عامة' },
  manageServices: { en: 'Manage Services', ar: 'إدارة الخدمات' },
  addService: { en: 'Add Service', ar: 'إضافة خدمة' },
  editService: { en: 'Edit Service', ar: 'تعديل خدمة' },
  deleteService: { en: 'Delete Service', ar: 'حذف خدمة' },
  serviceNameAr: { en: 'Service Name (Arabic)', ar: 'اسم الخدمة (عربي)' },
  serviceNameEn: { en: 'Service Name (English)', ar: 'اسم الخدمة (إنجليزي)' },
  serviceDescAr: { en: 'Description (Arabic)', ar: 'الوصف (عربي)' },
  serviceDescEn: { en: 'Description (English)', ar: 'الوصف (إنجليزي)' },
  selectCategory: { en: 'Select Category', ar: 'اختر التصنيف' },
  price: { en: 'Price', ar: 'السعر' },
  discountPrice: { en: 'Discounted Price', ar: 'السعر بعد الخصم' },
  discountStart: { en: 'Discount Start Date', ar: 'تاريخ بداية الخصم' },
  discountEnd: { en: 'Discount End Date', ar: 'تاريخ نهاية الخصم' },
  daysLeft: { en: 'days left', ar: 'أيام متبقية' },
  seoKeywords: { en: 'SEO Keywords', ar: 'كلمات دلالية SEO' },
  seoPlaceholder: { en: 'e.g. ecommerce, setup', ar: 'مثال: تجارة الكترونية، سلة، تسويق' },
  isFeatured: { en: 'Featured Service', ar: 'خدمة مميزة' },
  new: { en: 'New', ar: 'جديد' },
  manageCourses: { en: 'Manage Courses', ar: 'إدارة الدورات' },
  addCourse: { en: 'Add Course', ar: 'إضافة دورة' },
  editCourse: { en: 'Edit Course', ar: 'تعديل دورة' },
  deleteCourse: { en: 'Delete Course', ar: 'حذف دورة' },
  courseNameAr: { en: 'Course Name (Arabic)', ar: 'اسم الدورة (عربي)' },
  courseNameEn: { en: 'Course Name (English)', ar: 'اسم الدورة (إنجليزي)' },
  videoUrl: { en: 'Video URL', ar: 'رابط الفيديو' },
  thumbnailUrl: { en: 'Thumbnail URL', ar: 'رابط صورة الفيديو' },
  introVideoUrl: { en: 'Intro Video URL', ar: 'رابط فيديو المقدمة' },
  deleteConfirm: { en: 'Are you sure?', ar: 'هل أنت متأكد؟' },
  deleteMsg: { en: 'You are about to permanently delete this item. This action cannot be undone.', ar: 'أنت على وشك حذف هذا العنصر نهائياً. لا يمكن التراجع عن هذا الإجراء.' },
  courseContent: { en: 'Course Content', ar: 'محتوى الدورة' },
  addLesson: { en: 'Add Lesson', ar: 'إضافة درس' },
  updateLesson: { en: 'Update Lesson', ar: 'تحديث الدرس' },
  cancelEdit: { en: 'Cancel Edit', ar: 'إلغاء التعديل' },
  lessonTitle: { en: 'Lesson Title', ar: 'عنوان الدرس' },
  lessonDuration: { en: 'Duration', ar: 'المدة' },
  totalDuration: { en: 'Total Duration (Auto-calc)', ar: 'إجمالي المدة (حساب تلقائي)' },
  noLessons: { en: 'No lessons added yet.', ar: 'لم يتم إضافة دروس بعد.' },
  courseIncludes: { en: 'This course includes:', ar: 'تتضمن هذه الدورة:' },
  learningPoints: { en: "Learning Outcomes", ar: 'محاور الدورة (ماذا ستتعلم)' },
  addPoint: { en: 'Add Point', ar: 'أضف نقطة' },
  addFeature: { en: 'Add Feature', ar: 'أضف ميزة' },
  featureIcon: { en: 'Icon', ar: 'الرمز' },
  featureText: { en: 'Text', ar: 'النص' },
  remove: { en: 'Remove', ar: 'حذف' },
  whatYouWillLearn: { en: "What you'll learn", ar: 'ماذا ستتعلم' },
  moneyBack: { en: '30-Day Money-Back Guarantee', ar: 'ضمان استرداد الأموال لمدة 30 يوماً' },
  off: { en: 'OFF', ar: 'خصم' },
  discountOffers: { en: 'Discount & Offers', ar: 'الخصومات والعروض' },
  lastUpdated: { en: 'Last updated', ar: 'آخر تحديث' },
  previewCourse: { en: 'Preview Course', ar: 'معاينة الدورة' },
  preview: { en: 'Preview', ar: 'معاينة' },
  expandAll: { en: 'Expand all', ar: 'توسيع الكل' },
  intro: { en: 'Introduction', ar: 'مقدمة' },
  coursePreview: { en: 'Course Preview', ar: 'نظرة عامة على الدورة' },
  description: { en: 'Description', ar: 'الوصف' },
  ownedCourse: { en: 'You own this course', ar: 'أنت تمتلك هذه الدورة' },
  viewAllCourses: { en: 'View All Courses', ar: 'عرض جميع الدورات' },
  viewAllCategories: { en: 'View All Categories', ar: 'عرض جميع الأقسام' },
  learn1: { en: 'Master the core concepts', ar: 'إتقان المفاهيم الأساسية' },
  learn2: { en: 'Practical application', ar: 'تطبيق عملي' },
  learn3: { en: 'Expert guidance', ar: 'توجيه من الخبراء' },
  learn4: { en: 'Certification', ar: 'شهادة إتمام' },
  adminNotes: { en: 'Admin Notes', ar: 'ملاحظات المسؤول' },
  notesPlaceholder: { en: 'Write important reminders or tasks here...', ar: 'اكتب ملاحظات هامة أو مهام هنا...' },
  settings: { en: 'Settings', ar: 'الإعدادات' },
  siteIdentity: { en: 'Site Identity', ar: 'هوية الموقع' },
  contactInfo: { en: 'Contact Info', ar: 'معلومات التواصل' },
  socialMedia: { en: 'Social Media', ar: 'وسائل التواصل الاجتماعي' },
  siteNameLabel: { en: 'Site Name', ar: 'اسم الموقع' },
  logoUrl: { en: 'Logo URL', ar: 'رابط الشعار' },
  footerDesc: { en: 'Footer Description', ar: 'وصف الفوتر' },
  contactEmail: { en: 'Contact Email', ar: 'البريد الإلكتروني' },
  whatsapp: { en: 'WhatsApp Number', ar: 'رقم الواتساب' },
  settingsSaved: { en: 'Settings saved successfully!', ar: 'تم حفظ الإعدادات بنجاح!' },
  locationInfo: { en: 'Location Information', ar: 'بيانات الموقع' },
  city: { en: 'City', ar: 'المدينة' },
  country: { en: 'Country', ar: 'الدولة' },
  heroSettings: { en: 'Hero Banner Settings', ar: 'إعدادات البنر الرئيسي' },
  heroTitleLabel: { en: 'Hero Title', ar: 'عنوان البنر' },
  heroSubtitleLabel: { en: 'Hero Subtitle', ar: 'وصف البنر' },
  heroImageUrl: { en: 'Hero Image URL', ar: 'رابط صورة البنر' },
  heroBtn1Text: { en: 'Primary Button Text', ar: 'نص الزر الرئيسي' },
  heroBtn2Text: { en: 'Secondary Button Text', ar: 'نص الزر الثانوي' },
  heroBtnLink: { en: 'Button Link/Action', ar: 'رابط/وجهة الزر' },
  heroBtnPlaceholder: { en: 'e.g., services, courses, or consultant', ar: 'مثال: services, courses, أو consultant' },
  modules: { en: 'Modules & Visibility', ar: 'تفعيل الأقسام' },
  enableServices: { en: 'Enable Services Section', ar: 'تفعيل قسم الخدمات' },
  enableCourses: { en: 'Enable Courses Section', ar: 'تفعيل قسم الدورات' },
  enableProjects: { en: 'Enable Ready Projects Section', ar: 'تفعيل قسم المشاريع الجاهزة' },
  enableBlog: { en: 'Enable Blog Section', ar: 'تفعيل قسم المدونة' },
  enableAI: { en: 'Enable Al-Mutammam Automated Consultant', ar: 'تفعيل مستشار المتمم الآلي' },
  additionalSettings: { en: 'Additional Settings', ar: 'إعدادات إضافية' },
  languages: { en: 'Languages', ar: 'اللغات' },
  enableAr: { en: 'Enable Arabic Language', ar: 'تفعيل اللغة العربية' },
  enableEn: { en: 'Enable English Language', ar: 'تفعيل اللغة الإنجليزية' },
  currencies: { en: 'Currencies', ar: 'العملات' },
  enableSAR: { en: 'Enable SAR Currency', ar: 'تفعيل عملة الريال السعودي' },
  enableUSD: { en: 'Enable USD Currency', ar: 'تفعيل عملة الدولار الأمريكي' },
  infoPages: { en: 'Information Pages', ar: 'الصفحات التعريفية' },
  addPage: { en: 'Add New Page', ar: 'إضافة صفحة جديدة' },
  editPage: { en: 'Edit Page', ar: 'تعديل الصفحة' },
  pageTitleAr: { en: 'Page Title (Arabic)', ar: 'عنوان الصفحة (عربي)' },
  pageTitleEn: { en: 'Page Title (English)', ar: 'عنوان الصفحة (إنجليزي)' },
  pageContentAr: { en: 'Content (Arabic)', ar: 'المحتوى (عربي)' },
  pageContentEn: { en: 'Content (English)', ar: 'المحتوى (إنجليزي)' },
  slug: { en: 'Page Slug', ar: 'رابط الصفحة (Slug)' },
  deletePage: { en: 'Delete Page', ar: 'حذف الصفحة' },
  viewPage: { en: 'View Page', ar: 'عرض الصفحة' },
  systemPageMsg: { en: 'This is a system page and cannot be deleted.', ar: 'هذه صفحة أساسية ولا يمكن حذفها.' },
  manageReviews: { en: 'Reviews Management', ar: 'إدارة التقييمات' },
  approve: { en: 'Approve', ar: 'موافقة' },
  reject: { en: 'Reject', ar: 'رفض' },
  reply: { en: 'Reply', ar: 'رد' },
  adminReply: { en: 'Admin Reply', ar: 'رد الإدارة' },
  awaitingApproval: { en: 'Awaiting Approval', ar: 'بانتظار الموافقة' },
  approved: { en: 'Approved', ar: 'مقبول' },
  rejected: { en: 'Rejected', ar: 'مرفوض' },
  reviewPendingMsg: { en: 'Your review has been submitted and is pending approval.', ar: 'تم إرسال تقييمك وهو بانتظار موافقة الإدارة.' },
  itemName: { en: 'Product', ar: 'المنتج' },
  reviewContent: { en: 'Review Content', ar: 'محتوى التقييم' },
  writeReply: { en: 'Write a reply...', ar: 'اكتب رداً...' },
  getInTouch: { en: 'Get in Touch', ar: 'تواصل معنا' },
  contactDesc: { en: 'We are here to help and answer any question you might have. We look forward to hearing from you.', ar: 'نحن هنا للمساعدة والإجابة على أي استفسار لديك. نتطلع لسماع صوتك.' },
  callUs: { en: 'Call Us', ar: 'اتصل بنا' },
  emailUs: { en: 'Email Us', ar: 'راسلنا' },
  visitUs: { en: 'Visit Us', ar: 'زرنا' },
  sendMessage: { en: 'Send Message', ar: 'إرسال رسالة' },
  fullName: { en: 'Full Name', ar: 'الاسم الكامل' },
  email: { en: 'Email Address', ar: 'البريد الإلكتروني' },
  subject: { en: 'Subject', ar: 'الموضوع' },
  message: { en: 'Message', ar: 'الرسالة' },
  messageSent: { en: 'Message Sent Successfully!', ar: 'تم إرسال الرسالة بنجاح!' },
  messageSentDesc: { en: 'Thank you for contacting us. We will get back to you shortly.', ar: 'شكراً لتواصلك معنا. سنرد عليك في أقرب وقت ممكن.' },
  workingHours: { en: 'Working Hours', ar: 'ساعات العمل' },
  workingHoursDesc: { en: 'Sun - Thu: 9:00 AM - 5:00 PM', ar: 'الأحد - الخميس: 9:00 ص - 5:00 م' },
  // Checkout Translations
  checkoutTitle: { en: 'Complete Your Order', ar: 'إتمام الطلب' },
  customerPhone: { en: 'Phone Number', ar: 'رقم الجوال' },
  notes: { en: 'Notes / Remarks', ar: 'ملاحظات' },
  checkoutNotice: { en: 'Our team will contact you shortly after receiving your order.', ar: 'سيتواصل معك فريق العمل في أقرب وقت ممكن بعد استلام الطلب.' },
  agreeToTerms: { en: 'I agree to the Terms & Policy', ar: 'أوافق على سياسة الموقع والشروط' },
  sendOrder: { en: 'Send Order', ar: 'أرسل الطلب' },
  orderSuccessTitle: { en: 'Thank You!', ar: 'شكراً لك!' },
  orderSuccessDesc: { en: 'Your order is under review. We will contact you soon.', ar: 'طلبك قيد المراجعة. سنتواصل معك قريباً.' },
  // Invoice & Admin Order Details
  invoices: { en: 'Invoices', ar: 'الفواتير' },
  invoiceId: { en: 'Invoice #', ar: 'رقم الفاتورة' },
  orderDetails: { en: 'Order Details', ar: 'تفاصيل الطلب' },
  customerInfo: { en: 'Customer Info', ar: 'بيانات العميل' },
  orderSummary: { en: 'Order Summary', ar: 'ملخص الطلب' },
  subtotal: { en: 'Subtotal', ar: 'المجموع الفرعي' },
  discount: { en: 'Discount', ar: 'الخصم' },
  changeStatus: { en: 'Change Status', ar: 'تغيير الحالة' },
  invoiceGenerated: { en: 'Invoice generated successfully.', ar: 'تم إنشاء الفاتورة بنجاح.' },
  sendWhatsApp: { en: 'Send via WhatsApp', ar: 'أرسل عبر واتساب' },
  downloadInvoice: { en: 'Download Invoice', ar: 'تحميل الفاتورة' },
  invoiceFor: { en: 'Invoice for order', ar: 'فاتورة الطلب' },
  items: { en: 'Items', ar: 'العناصر' },
  viewDetails: { en: 'View Details', ar: 'عرض التفاصيل' },
  markPaid: { en: 'Mark as Paid', ar: 'تحديد كمدفوع' },
  markCompleted: { en: 'Mark as Completed', ar: 'تحديد كمكتمل' },
  markCancelled: { en: 'Cancel Order', ar: 'إلغاء الطلب' },
  printInvoice: { en: 'Print Invoice', ar: 'طباعة الفاتورة' },
  billTo: { en: 'Bill To', ar: 'فاتورة إلى' }
};

export const DEFAULT_INFO_PAGES: InfoPage[] = [
  {
    id: 'page-about',
    titleEn: 'About Us',
    titleAr: 'من نحن',
    contentEn: 'Namaa is a leading platform dedicated to empowering entrepreneurs and businesses...',
    contentAr: 'نماء هي منصة رائدة مكرسة لتمكين رواد الأعمال والشركات...',
    slug: 'about-us',
    isSystem: true
  },
  {
    id: 'page-privacy',
    titleEn: 'Privacy Policy',
    titleAr: 'سياسة الخصوصية',
    contentEn: 'We value your privacy and are committed to protecting your personal data...',
    contentAr: 'نحن نقدر خصوصيتك ونلتزم بحماية بياناتك الشخصية...',
    slug: 'privacy-policy',
    isSystem: true
  },
  {
    id: 'page-terms',
    titleEn: 'Terms of Service',
    titleAr: 'شروط الخدمة',
    contentEn: 'By using our services, you agree to the following terms and conditions...',
    contentAr: 'باستخدامك لخدماتنا، فإنك توافق على الشروط والأحكام التالية...',
    slug: 'terms-of-service',
    isSystem: true
  }
];

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  { id: 'business', titleEn: 'Business Management', titleAr: 'إدارة الأعمال', descriptionEn: 'Services to help you manage and grow your business.', descriptionAr: 'خدمات لمساعدتك في إدارة وتنمية أعمالك.', icon: 'Briefcase', order: 1, color: '#3b82f6' },
  { id: 'marketing', titleEn: 'Marketing & Growth', titleAr: 'التسويق والنمو', descriptionEn: 'Boost your brand visibility and reach more customers.', descriptionAr: 'عزز ظهور علامتك التجارية واصل إلى المزيد من العملاء.', icon: 'TrendingUp', order: 2, color: '#10b981' },
  { id: 'tech', titleEn: 'Technology', titleAr: 'التقنية', descriptionEn: 'Technical solutions for your digital presence.', descriptionAr: 'حلول تقنية لوجودك الرقمي.', icon: 'Cpu', order: 3, color: '#8b5cf6' }
];

export const COURSE_CATEGORIES: ServiceCategory[] = [
  { id: 'business', titleEn: 'Entrepreneurship', titleAr: 'ريادة الأعمال', descriptionEn: 'Learn how to start and scale your business.', descriptionAr: 'تعلم كيفية بدء وتوسيع نطاق عملك.', icon: 'Rocket', order: 1, color: '#f59e0b' },
  { id: 'marketing', titleEn: 'Digital Marketing', titleAr: 'التسويق الرقمي', descriptionEn: 'Master the art of online marketing.', descriptionAr: 'أتقن فن التسويق عبر الإنترنت.', icon: 'Megaphone', order: 2, color: '#ec4899' },
  { id: 'tech', titleEn: 'Tech Skills', titleAr: 'مهارات تقنية', descriptionEn: 'Upgrade your technical skills.', descriptionAr: 'طور مهاراتك التقنية.', icon: 'Code', order: 3, color: '#3b82f6' }
];

export const PROJECT_CATEGORIES: ServiceCategory[] = [
  { id: 'ecommerce', titleEn: 'E-commerce', titleAr: 'المتاجر الإلكترونية', descriptionEn: 'Ready-made online stores.', descriptionAr: 'متاجر إلكترونية جاهزة.', icon: 'ShoppingBag', order: 1, color: '#f97316' },
  { id: 'saas', titleEn: 'SaaS', titleAr: 'البرمجيات كخدمة', descriptionEn: 'Software as a Service templates.', descriptionAr: 'قوالب البرمجيات كخدمة.', icon: 'Cloud', order: 2, color: '#06b6d4' },
  { id: 'landing', titleEn: 'Landing Pages', titleAr: 'صفحات الهبوط', descriptionEn: 'High converting landing pages.', descriptionAr: 'صفحات هبوط عالية التحويل.', icon: 'Layout', order: 3, color: '#8b5cf6' }
];

export const BLOG_CATEGORIES: BlogCategory[] = [
  { id: 'business', titleEn: 'Business Tips', titleAr: 'نصائح تجارية', color: '#3b82f6' },
  { id: 'tech', titleEn: 'Tech Trends', titleAr: 'توجهات التقنية', color: '#10b981' },
  { id: 'marketing', titleEn: 'Marketing Guides', titleAr: 'أدلة التسويق', color: '#f59e0b' }
];

export const SERVICES: Service[] = [
  {
    id: 'srv_1',
    titleEn: 'Company Formation in Saudi Arabia',
    titleAr: 'تأسيس الشركات في السعودية',
    descriptionEn: 'Complete legal and administrative setup for your new company in KSA.',
    descriptionAr: 'تأسيس قانوني وإداري كامل لشركتك الجديدة في المملكة العربية السعودية.',
    icon: 'Building',
    category: 'business',
    price: 5000,
    purchaseCount: 120,
    isPopular: true,
    rating: 4.8,
    reviews: []
  },
  {
    id: 'srv_2',
    titleEn: 'Digital Marketing Strategy',
    titleAr: 'استراتيجية التسويق الرقمي',
    descriptionEn: 'A comprehensive marketing plan tailored to your business goals.',
    descriptionAr: 'خطة تسويقية شاملة مصممة خصيصاً لأهداف عملك.',
    icon: 'TrendingUp',
    category: 'marketing',
    price: 2500,
    purchaseCount: 85,
    rating: 4.5,
    reviews: []
  },
  {
    id: 'srv_3',
    titleEn: 'Feasibility Study',
    titleAr: 'دراسة جدوى اقتصادية',
    descriptionEn: 'Professional financial and market feasibility study for your project.',
    descriptionAr: 'دراسة جدوى مالية وتسويقية احترافية لمشروعك لضمان نجاحه.',
    icon: 'FileText',
    category: 'business',
    price: 3500,
    purchaseCount: 60,
    rating: 4.7,
    reviews: []
  },
  {
    id: 'srv_4',
    titleEn: 'Trademark Registration',
    titleAr: 'تسجيل العلامات التجارية',
    descriptionEn: 'Protect your brand identity with official trademark registration.',
    descriptionAr: 'احمِ هوية علامتك التجارية من خلال التسجيل الرسمي للعلامة.',
    icon: 'ShieldCheck',
    category: 'business',
    price: 1500,
    purchaseCount: 200,
    rating: 4.9,
    isPopular: true,
    reviews: []
  },
  {
    id: 'srv_5',
    titleEn: 'Mobile App Development',
    titleAr: 'تصميم وبرمجة تطبيقات الجوال',
    descriptionEn: 'Custom iOS and Android apps built with the latest technologies.',
    descriptionAr: 'تطبيقات مخصصة لنظامي iOS و Android مبنية بأحدث التقنيات.',
    icon: 'Cpu',
    category: 'tech',
    price: 15000,
    purchaseCount: 30,
    rating: 4.6,
    reviews: []
  },
  {
    id: 'srv_6',
    titleEn: 'SEO Optimization Package',
    titleAr: 'باقة تحسين محركات البحث SEO',
    descriptionEn: 'Boost your website ranking on Google and increase organic traffic.',
    descriptionAr: 'ارفع ترتيب موقعك في جوجل وزد من الزيارات الطبيعية.',
    icon: 'Search',
    category: 'marketing',
    price: 2000,
    purchaseCount: 150,
    rating: 4.8,
    reviews: []
  },
  {
    id: 'srv_7',
    titleEn: 'Social Media Management',
    titleAr: 'إدارة حسابات التواصل الاجتماعي',
    descriptionEn: 'Content creation, posting, and community management for your brand.',
    descriptionAr: 'إنشاء المحتوى والنشر وإدارة المجتمع لعلامتك التجارية.',
    icon: 'Share2',
    category: 'marketing',
    price: 4000,
    purchaseCount: 95,
    rating: 4.7,
    reviews: []
  },
  {
    id: 'srv_8',
    titleEn: 'UI/UX Design Service',
    titleAr: 'تصميم تجربة وواجهة المستخدم',
    descriptionEn: 'Create intuitive and beautiful interfaces for your digital products.',
    descriptionAr: 'ابتكار واجهات جذابة وسهلة الاستخدام لمنتجاتك الرقمية.',
    icon: 'Palette',
    category: 'tech',
    price: 5000,
    purchaseCount: 45,
    rating: 4.9,
    reviews: []
  }
];

export const COURSES: Course[] = [
  {
    id: 'crs_1',
    titleEn: 'Entrepreneurship 101',
    titleAr: 'مبادئ ريادة الأعمال',
    descriptionEn: 'A complete guide to starting your own business from scratch.',
    descriptionAr: 'دليل كامل لبدء مشروعك الخاص من الصفر.',
    thumbnailColor: 'bg-blue-500',
    duration: '10h 30m',
    lessons: [
       { id: 'l1', title: 'Introduction to Business', duration: '45m', videoUrl: '' },
       { id: 'l2', title: 'Market Research', duration: '1h 20m', videoUrl: '' }
    ],
    price: 199,
    category: 'business',
    purchaseCount: 1500,
    isPopular: true,
    rating: 4.9,
    reviews: [],
    learningPoints: ['Business Basics', 'Market Strategy', 'Financial Planning'],
    features: [{ id: 'f1', icon: 'Check', text: 'Certificate of Completion' }]
  },
  {
    id: 'crs_2',
    titleEn: 'Digital Marketing Mastery',
    titleAr: 'احتراف التسويق الرقمي',
    descriptionEn: 'Learn SEO, Social Media, and PPC to grow any business.',
    descriptionAr: 'تعلم السيو، التواصل الاجتماعي، والإعلانات الممولة لتنمية أي مشروع.',
    thumbnailColor: 'bg-pink-500',
    duration: '15h',
    lessons: [],
    price: 299,
    category: 'marketing',
    purchaseCount: 850,
    rating: 4.7,
    reviews: [],
    learningPoints: ['SEO Advanced', 'Facebook Ads', 'Google Analytics'],
    features: [{ id: 'f1', icon: 'Check', text: 'Real-world Projects' }]
  },
  {
    id: 'crs_3',
    titleEn: 'React Native for Beginners',
    titleAr: 'رياكت نيتف للمبتدئين',
    descriptionEn: 'Build cross-platform mobile apps using React and JavaScript.',
    descriptionAr: 'بناء تطبيقات جوال متعددة المنصات باستخدام React و JavaScript.',
    thumbnailColor: 'bg-indigo-500',
    duration: '20h',
    lessons: [],
    price: 150,
    category: 'tech',
    purchaseCount: 1200,
    isPopular: true,
    rating: 4.8,
    reviews: [],
    learningPoints: ['Hooks', 'Navigation', 'State Management'],
    features: [{ id: 'f1', icon: 'Code', text: 'Source Code Included' }]
  },
  {
    id: 'crs_4',
    titleEn: 'Financial Management for Startups',
    titleAr: 'الإدارة المالية للشركات الناشئة',
    descriptionEn: 'Understand cash flow, P&L, and funding strategies.',
    descriptionAr: 'فهم التدفق النقدي، حسابات الأرباح والخسائر، واستراتيجيات التمويل.',
    thumbnailColor: 'bg-green-600',
    duration: '8h 45m',
    lessons: [],
    price: 250,
    category: 'business',
    purchaseCount: 300,
    rating: 4.6,
    reviews: [],
    learningPoints: ['Budgeting', 'Investment Readiness', 'Valuation'],
    features: [{ id: 'f1', icon: 'FileText', text: 'Templates Included' }]
  }
];

export const PROJECTS: Project[] = [
  {
    id: 'prj_1',
    titleEn: 'Modern E-commerce Store',
    titleAr: 'متجر إلكتروني عصري',
    descriptionEn: 'A fully functional e-commerce store built with React and Node.js.',
    descriptionAr: 'متجر إلكتروني متكامل الوظائف مبني باستخدام React و Node.js.',
    price: 999,
    category: 'ecommerce',
    purchaseCount: 50,
    rating: 4.7,
    reviews: [],
    techStack: ['React', 'Node.js', 'MongoDB'],
    features: ['Responsive Design', 'Admin Panel', 'Payment Gateway']
  },
  {
    id: 'prj_2',
    titleEn: 'Restaurant POS System',
    titleAr: 'نظام نقاط بيع للمطاعم',
    descriptionEn: 'Cloud-based Point of Sale system for restaurants and cafes.',
    descriptionAr: 'نظام نقاط بيع سحابي للمطاعم والمقاهي مع إدارة طاولات.',
    price: 1500,
    category: 'saas',
    purchaseCount: 25,
    rating: 4.9,
    reviews: [],
    techStack: ['Vue.js', 'Laravel', 'MySQL'],
    features: ['Table Management', 'Inventory', 'Kitchen Display']
  },
  {
    id: 'prj_3',
    titleEn: 'Real Estate Landing Page',
    titleAr: 'صفحة هبوط عقارية',
    descriptionEn: 'High conversion landing page template for real estate projects.',
    descriptionAr: 'قالب صفحة هبوط عالي التحويل للمشاريع العقارية.',
    price: 199,
    category: 'landing',
    purchaseCount: 150,
    rating: 4.5,
    reviews: [],
    techStack: ['Next.js', 'Tailwind CSS'],
    features: ['Lead Form', 'Gallery', 'Map Integration']
  },
  {
    id: 'prj_4',
    titleEn: 'Multi-Vendor Marketplace',
    titleAr: 'منصة متعددة البائعين',
    descriptionEn: 'Amazon-like marketplace solution with vendor dashboards.',
    descriptionAr: 'حل متجر شبيه بأمازون مع لوحات تحكم مستقلة للبائعين.',
    price: 2500,
    category: 'ecommerce',
    purchaseCount: 15,
    isPopular: true,
    rating: 4.8,
    reviews: [],
    techStack: ['MERN Stack', 'Redux', 'Stripe'],
    features: ['Vendor Portal', 'Commission System', 'Review System']
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'post_1',
    titleEn: 'Top 10 Business Trends in 2024',
    titleAr: 'أهم 10 اتجاهات للأعمال في 2024',
    contentEn: 'Here are the top business trends you need to watch out for...',
    contentAr: 'إليك أهم اتجاهات الأعمال التي يجب عليك متابعتها...',
    excerptEn: 'Discover the key trends shaping the business landscape this year.',
    excerptAr: 'اكتشف الاتجاهات الرئيسية التي تشكل مشهد الأعمال هذا العام.',
    coverImageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=800',
    authorName: 'Admin',
    publishDate: '2024-03-15',
    categoryId: 'business',
    readTime: '5 min read'
  },
  {
    id: 'post_2',
    titleEn: 'The Future of AI in Marketing',
    titleAr: 'مستقبل الذكاء الاصطناعي في التسويق',
    contentEn: 'AI is revolutionizing how we approach digital marketing...',
    contentAr: 'الذكاء الاصطناعي يحدث ثورة في كيفية تعاملنا مع التسويق الرقمي...',
    excerptEn: 'How AI tools are changing the game for marketers.',
    excerptAr: 'كيف تغير أدوات الذكاء الاصطناعي قواعد اللعبة للمسوقين.',
    coverImageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&q=80&w=800',
    authorName: 'Sarah Tech',
    publishDate: '2024-03-20',
    categoryId: 'tech',
    readTime: '7 min read'
  },
  {
    id: 'post_3',
    titleEn: 'How to Start a LLC in Saudi Arabia',
    titleAr: 'كيف تبدأ شركة ذات مسؤولية محدودة في السعودية',
    contentEn: 'A step-by-step guide to legal company formation...',
    contentAr: 'دليل خطوة بخطوة لتأسيس الشركات القانوني في المملكة...',
    excerptEn: 'Everything you need to know about starting your business in KSA.',
    excerptAr: 'كل ما تحتاج معرفته عن بدء مشروعك في المملكة العربية السعودية.',
    coverImageUrl: 'https://images.unsplash.com/photo-1554469384-e58fac16e23a?auto=format&fit=crop&q=80&w=800',
    authorName: 'Legal Expert',
    publishDate: '2024-03-25',
    categoryId: 'business',
    readTime: '10 min read'
  },
  {
    id: 'post_4',
    titleEn: 'Growth Hacking Strategies',
    titleAr: 'استراتيجيات نمو المشاريع (Growth Hacking)',
    contentEn: 'Actionable tips to grow your user base fast...',
    contentAr: 'نصائح عملية لتنمية قاعدة مستخدميك بسرعة...',
    excerptEn: 'Proven tactics to scale your startup effectively.',
    excerptAr: 'تكتيكات مثبتة لتوسيع نطاق شركتك الناشئة بفعالية.',
    coverImageUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&q=80&w=800',
    authorName: 'Growth Guru',
    publishDate: '2024-04-01',
    categoryId: 'marketing',
    readTime: '6 min read'
  }
];

export const MOCK_ORDERS: Order[] = [
  { id: 'ord_1', customerName: 'Ahmed Ali', customerPhone: '0501234567', customerEmail: 'ahmed@example.com', serviceId: 'srv_1', status: 'completed', date: '2024-02-20', amount: 5000, invoiceId: 'inv_1001' },
  { id: 'ord_2', customerName: 'Sara Ahmed', customerPhone: '0509876543', customerEmail: 'sara@example.com', serviceId: 'crs_1', status: 'in_progress', date: '2024-02-25', amount: 199 }
];
